# Generated by Django 5.2.4 on 2025-08-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompttemplate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
