# Generated by Django 5.2.4 on 2025-08-05 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_prompttemplate_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompttemplate',
            old_name='title',
            new_name='prompt_title',
        ),
        migrations.RemoveField(
            model_name='prompthistory',
            name='input_data',
        ),
    ]
