# Generated by Django 5.2.4 on 2025-08-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_prompthistory_input_data_alter_prompttemplate_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prompttemplate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Prompt Template', 'verbose_name_plural': 'Prompt Templates'},
        ),
        migrations.RemoveField(
            model_name='prompttemplate',
            name='description',
        ),
        migrations.RemoveField(
            model_name='prompttemplate',
            name='visibility',
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='ai_feedback',
            field=models.TextField(blank=True, help_text='AI-generated suggestions or review comments for this prompt', null=True),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='clarity_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AI-evaluated clarity score (1.00 to 10.00)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', help_text='AI-evaluated priority level', max_length=10),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical'), ('marketing', 'Marketing'), ('educational', 'Educational'), ('design', 'Design'), ('other', 'Other')], default='other', help_text='AI-assigned category (e.g., Technical, Marketing, Educational)', max_length=50),
        ),
    ]
